### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by chen9965** [antonis19/autobrowse#2]
PS C:\Users\freedom\Desktop\autobrowse-main> & C:/Users/freedom/.conda/envs/py39/python.exe c:/Users/freedom/Desktop/autobrowse-main/autobrowse.py
Traceback (most recent call last):
  File "c:\Users\freedom\Desktop\autobrowse-main\autobrowse.py", line 240, in <module>
    autobrowse = AutoBrowse(config = agent_config.config)
  File "c:\Users\freedom\Desktop\autobrowse-main\autobrowse.py", line 46, in __init__
    self.init_html_assistant(config["html_assistant"].get("model"), config["html_assistant"].get("system_message"))
  File "c:\Users\freedom\Desktop\autobrowse-main\autobrowse.py", line 143, in init_html_assistant
    self.html_proxy = RetrieveHTMLProxyAgent(
  File "c:\Users\freedom\Desktop\autobrowse-main\retrieve_html_proxy_agent.py", line 76, in __init__
    self.connect_websocket()
  File "c:\Users\freedom\Desktop\autobrowse-main\retrieve_html_proxy_agent.py", line 81, in connect_websocket
    self.websocket = asyncio.get_event_loop().run_until_complete(websockets.connect(self.browser_console_uri))
  File "C:\Users\freedom\.conda\envs\py39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\freedom\.conda\envs\py39\lib\asyncio\tasks.py", line 688, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "C:\Users\freedom\.conda\envs\py39\lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\freedom\.conda\envs\py39\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "C:\Users\freedom\.conda\envs\py39\lib\asyncio\base_events.py", line 1070, in create_connection
    raise exceptions[0]
  File "C:\Users\freedom\.conda\envs\py39\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\freedom\.conda\envs\py39\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\freedom\.conda\envs\py39\lib\asyncio\proactor_events.py", line 703, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\freedom\.conda\envs\py39\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\freedom\.conda\envs\py39\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

**Comment by antonis19** [comment]
You need to be running the browser console before running the main program:

https://github.com/antonis19/autobrowse/tree/main/browser-console
